### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by HelgaListopad** [Pyrus-vagus/webix-app#2]
Although the overall result is good, there are a few minor issues to improve (some of them can turn into a reason for suffering in real-world projects).

1. To get a bit more clear appearance, the template in the header should be `borderless`.
2. Buttons: `autowidth` should be always boolean.
3. List CSS: `border: none` removes borders and changes the height of an item, while the sizing logic in JS has no idea about that. This may be an issue on a big dataset (improper scroll position, unexpected result of auto-sizing, etc.). 
A `transparent` colour for borders is always safe.

4. Form:
- `type: "section"` modifies label to upper case automatically, so there's no need for additional actions,
- (not really a mistake) FYI: `autoheight` is a feature of data components (table, template) *and* form, but it's not supported by a regular layout. So instead of `autoheight:false` it's more common to use a [spacer](https://slides.com/ihelga/webixlayouts#/18) to fill the rest of the available area. 

5. General:
I wouldn't recommend addressing IDs in code through initial objects (`movieList.id`, `form.id`). 
These objects were used in `webix.ui` only once and there's no any further reference/link to a real UI instance. 
However, `form.id` will refer to a current value of this property at the moment the function (for example, `click` on a button) is called (there is no [closure](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures) in the code and no need for it). 
The best option to keep IDs consistent is to move them to `const` values on top of the page and then use them in the configuration objects and related methods.

**Comment by Pyrus-vagus** [comment]
Hi @HelgaListopad
Thanks a lot for your review!
Please, see the amendments I implemented in [this pull-request](https://github.com/Pyrus-vagus/webix-app/pull/3)

**Comment by HelgaListopad** [comment]
@Pyrus-vagus yep, all required changes are in place (make sure you merge it). Thank you!
